name: "Build and Publish, Deploy Docker Image"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "**"
      - "!.github/**"

jobs:
  build-publish:
    uses: chnm/.github/.github/workflows/django--build-publish.yml@main
    secrets: inherit
    with:

      container-registry: "ghcr.io"
      container-image-name: "lasfera"
      
      django-context-root: "."

      website-devl-fqdn: "dev.lasfera.rrchnm.org"
      website-prod-fqdn: "dev.lasfera.rrchnm.org"
      
  deploy:
    uses: chnm/.github/.github/workflows/django--deploy.yml@main
    needs: [build-publish]
    if: github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      website-devl-fqdn: "dev.lasfera.rrchnm.org"
      website-prod-fqdn: "dev.lasfera.rrchnm.org"
